"""sprint_1_mvp_schema

Revision ID: e29d3f46feb9
Revises: 7c590bb021a2
Create Date: 2026-09-09 18:31:38.128028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29d3f46feb9'
down_revision: Union[str, None] = '7c590bb021a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('service_area', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooperatives_id'), 'cooperatives', ['id'], unique=False)
    op.create_table('review_questions',
    sa.Column('target_role', sa.Enum('CUSTOMER', 'WORKER', name='reviewerrole', native_enum=False, length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_questions_id'), 'review_questions', ['id'], unique=False)
    op.create_table('service_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_rate_per_minute', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_billable_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_categories_id'), 'service_categories', ['id'], unique=False)
    op.create_index(op.f('ix_service_categories_name'), 'service_categories', ['name'], unique=True)
    op.create_table('service_tasks',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_tasks_category_id'), 'service_tasks', ['category_id'], unique=False)
    op.create_index(op.f('ix_service_tasks_id'), 'service_tasks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('role', sa.Enum('CUSTOMER', 'WORKER', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cooperative_id'), 'users', ['cooperative_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('customer_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('gigs',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('gig_type', sa.Enum('NORMAL', 'VISITATION', name='gigtype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'ACCEPTANCE_OPEN', 'WORKER_SELECTED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETION_SUBMITTED', 'CUSTOMER_CONFIRMED', 'PAYMENT_PENDING', 'PAYMENT_CUSTOMER_PAID', 'PAYMENT_WORKER_CONFIRMED', 'COMPLETED', 'CANCELLED', name='gigstatus', native_enum=False, length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('google_maps_link', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_start_time', sa.Time(), nullable=True),
    sa.Column('scheduled_end_time', sa.Time(), nullable=True),
    sa.Column('expected_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('acceptance_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('material_procurement_mode', sa.Enum('CUSTOMER_PURCHASES', 'WORKER_PURCHASES', name='materialprocurementmode', native_enum=False, length=30), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_billable_minutes_snapshot', sa.Integer(), nullable=True),
    sa.Column('base_rate_per_minute_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selected_worker_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gigs_category_id'), 'gigs', ['category_id'], unique=False)
    op.create_index(op.f('ix_gigs_cooperative_id'), 'gigs', ['cooperative_id'], unique=False)
    op.create_index(op.f('ix_gigs_customer_id'), 'gigs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gigs_id'), 'gigs', ['id'], unique=False)
    op.create_index(op.f('ix_gigs_scheduled_date'), 'gigs', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_gigs_selected_worker_id'), 'gigs', ['selected_worker_id'], unique=False)
    op.create_index(op.f('ix_gigs_status'), 'gigs', ['status'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('aadhaar_document_url', sa.Text(), nullable=True),
    sa.Column('aadhaar_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('completion_confirmations',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('response_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_confirmations_customer_id'), 'completion_confirmations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_completion_confirmations_gig_id'), 'completion_confirmations', ['gig_id'], unique=False)
    op.create_index(op.f('ix_completion_confirmations_id'), 'completion_confirmations', ['id'], unique=False)
    op.create_table('completion_submissions',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_submissions_gig_id'), 'completion_submissions', ['gig_id'], unique=False)
    op.create_index(op.f('ix_completion_submissions_id'), 'completion_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_completion_submissions_worker_id'), 'completion_submissions', ['worker_id'], unique=False)
    op.create_table('conversations',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_customer_id'), 'conversations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_conversations_gig_id'), 'conversations', ['gig_id'], unique=True)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_worker_id'), 'conversations', ['worker_id'], unique=False)
    op.create_table('gig_cancellations',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('cancelled_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gig_cancellations_cancelled_by'), 'gig_cancellations', ['cancelled_by'], unique=False)
    op.create_index(op.f('ix_gig_cancellations_gig_id'), 'gig_cancellations', ['gig_id'], unique=False)
    op.create_index(op.f('ix_gig_cancellations_id'), 'gig_cancellations', ['id'], unique=False)
    op.create_table('gig_events',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gig_events_actor_id'), 'gig_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_gig_events_event_type'), 'gig_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_gig_events_gig_id'), 'gig_events', ['gig_id'], unique=False)
    op.create_index(op.f('ix_gig_events_id'), 'gig_events', ['id'], unique=False)
    op.create_index('ix_gig_events_timeline', 'gig_events', ['gig_id', 'created_at'], unique=False)
    op.create_table('gig_tasks',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('standard_duration_minutes_snapshot', sa.Integer(), nullable=False),
    sa.Column('base_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gig_id', 'task_id', name='uq_gig_task')
    )
    op.create_index(op.f('ix_gig_tasks_gig_id'), 'gig_tasks', ['gig_id'], unique=False)
    op.create_index(op.f('ix_gig_tasks_id'), 'gig_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_gig_tasks_task_id'), 'gig_tasks', ['task_id'], unique=False)
    op.create_table('gig_worker_opportunities',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'NOT_SELECTED', name='opportunitystatus', native_enum=False, length=20), nullable=False),
    sa.Column('base_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_score_snapshot', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('premium_percentage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('exact_wage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gig_id', 'worker_id', name='uq_gig_worker_opportunity')
    )
    op.create_index(op.f('ix_gig_worker_opportunities_gig_id'), 'gig_worker_opportunities', ['gig_id'], unique=False)
    op.create_index(op.f('ix_gig_worker_opportunities_id'), 'gig_worker_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_gig_worker_opportunities_status'), 'gig_worker_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_gig_worker_opportunities_worker_id'), 'gig_worker_opportunities', ['worker_id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_receipts_gig_id'), 'material_receipts', ['gig_id'], unique=False)
    op.create_index(op.f('ix_material_receipts_id'), 'material_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_material_receipts_worker_id'), 'material_receipts', ['worker_id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('gig_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('action_url', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_gig_id'), 'notifications', ['gig_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('payments',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CUSTOMER_PAID', 'WORKER_CONFIRMED', name='paymentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_gig_id'), 'payments', ['gig_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index('ix_payments_lookup', 'payments', ['gig_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_worker_id'), 'payments', ['worker_id'], unique=False)
    op.create_table('previous_worker_requests',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', 'RESCHEDULE_REQUESTED', 'EXPIRED', name='previousworkerrequeststatus', native_enum=False, length=30), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_previous_worker_requests_customer_id'), 'previous_worker_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_previous_worker_requests_gig_id'), 'previous_worker_requests', ['gig_id'], unique=False)
    op.create_index(op.f('ix_previous_worker_requests_id'), 'previous_worker_requests', ['id'], unique=False)
    op.create_index(op.f('ix_previous_worker_requests_status'), 'previous_worker_requests', ['status'], unique=False)
    op.create_index(op.f('ix_previous_worker_requests_worker_id'), 'previous_worker_requests', ['worker_id'], unique=False)
    op.create_table('reschedule_requests',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('proposed_start_time', sa.Time(), nullable=False),
    sa.Column('proposed_end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', 'ALTERNATIVE_PROPOSED', name='reschedulestatus', native_enum=False, length=30), nullable=False),
    sa.Column('responded_by', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reschedule_requests_gig_id'), 'reschedule_requests', ['gig_id'], unique=False)
    op.create_index(op.f('ix_reschedule_requests_id'), 'reschedule_requests', ['id'], unique=False)
    op.create_index(op.f('ix_reschedule_requests_requested_by'), 'reschedule_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_reschedule_requests_status'), 'reschedule_requests', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewee_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('CUSTOMER', 'WORKER', name='reviewerrole', native_enum=False, length=20), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gig_id', 'reviewer_id', 'reviewee_id', name='uq_review_direction')
    )
    op.create_index(op.f('ix_reviews_gig_id'), 'reviews', ['gig_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index('ix_reviews_reviewee', 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('visitation_proposals',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='visitationproposalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('customer_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitation_proposals_gig_id'), 'visitation_proposals', ['gig_id'], unique=False)
    op.create_index(op.f('ix_visitation_proposals_id'), 'visitation_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_visitation_proposals_status'), 'visitation_proposals', ['status'], unique=False)
    op.create_index(op.f('ix_visitation_proposals_worker_id'), 'visitation_proposals', ['worker_id'], unique=False)
    op.create_table('worker_availability',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_availability_day_of_week'), 'worker_availability', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_worker_availability_id'), 'worker_availability', ['id'], unique=False)
    op.create_index('ix_worker_availability_lookup', 'worker_availability', ['worker_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_worker_availability_worker_id'), 'worker_availability', ['worker_id'], unique=False)
    op.create_table('worker_categories',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'category_id', name='uq_worker_category')
    )
    op.create_index(op.f('ix_worker_categories_category_id'), 'worker_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_worker_categories_id'), 'worker_categories', ['id'], unique=False)
    op.create_index(op.f('ix_worker_categories_worker_id'), 'worker_categories', ['worker_id'], unique=False)
    op.create_table('worker_experience_records',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('participation_type', sa.Enum('PRIMARY_COMPLETION', 'ROOKIE_PARTICIPATION', name='participationtype', native_enum=False, length=30), nullable=False),
    sa.Column('complexity_value', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('experience_contribution', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_exp_lookup', 'worker_experience_records', ['worker_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_worker_experience_records_gig_id'), 'worker_experience_records', ['gig_id'], unique=False)
    op.create_index(op.f('ix_worker_experience_records_id'), 'worker_experience_records', ['id'], unique=False)
    op.create_index(op.f('ix_worker_experience_records_worker_id'), 'worker_experience_records', ['worker_id'], unique=False)
    op.create_table('worker_metrics',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('completed_jobs_count', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('bayesian_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('experience_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('worker_participations',
    sa.Column('gig_id', sa.Uuid(), nullable=False),
    sa.Column('inviting_worker_id', sa.Uuid(), nullable=False),
    sa.Column('additional_worker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='workerparticipationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('classification', sa.Enum('ROOKIE', 'EQUAL_SHARING', name='workerparticipationclassification', native_enum=False, length=30), nullable=False),
    sa.Column('experience_contribution', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['additional_worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gig_id'], ['gigs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviting_worker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_participations_additional_worker_id'), 'worker_participations', ['additional_worker_id'], unique=False)
    op.create_index(op.f('ix_worker_participations_gig_id'), 'worker_participations', ['gig_id'], unique=False)
    op.create_index(op.f('ix_worker_participations_id'), 'worker_participations', ['id'], unique=False)
    op.create_index(op.f('ix_worker_participations_inviting_worker_id'), 'worker_participations', ['inviting_worker_id'], unique=False)
    op.create_index('ix_worker_participations_lookup', 'worker_participations', ['gig_id', 'additional_worker_id'], unique=False)
    op.create_index(op.f('ix_worker_participations_status'), 'worker_participations', ['status'], unique=False)
    op.create_table('completion_evidence',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['completion_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completion_evidence_id'), 'completion_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_completion_evidence_submission_id'), 'completion_evidence', ['submission_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_thread', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('review_answers',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['review_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_answers_id'), 'review_answers', ['id'], unique=False)
    op.create_index(op.f('ix_review_answers_question_id'), 'review_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_review_answers_review_id'), 'review_answers', ['review_id'], unique=False)
    op.create_table('visitation_proposal_tasks',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('standard_duration_minutes_snapshot', sa.Integer(), nullable=False),
    sa.Column('base_price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['visitation_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitation_proposal_tasks_id'), 'visitation_proposal_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_visitation_proposal_tasks_proposal_id'), 'visitation_proposal_tasks', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_visitation_proposal_tasks_task_id'), 'visitation_proposal_tasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitation_proposal_tasks_task_id'), table_name='visitation_proposal_tasks')
    op.drop_index(op.f('ix_visitation_proposal_tasks_proposal_id'), table_name='visitation_proposal_tasks')
    op.drop_index(op.f('ix_visitation_proposal_tasks_id'), table_name='visitation_proposal_tasks')
    op.drop_table('visitation_proposal_tasks')
    op.drop_index(op.f('ix_review_answers_review_id'), table_name='review_answers')
    op.drop_index(op.f('ix_review_answers_question_id'), table_name='review_answers')
    op.drop_index(op.f('ix_review_answers_id'), table_name='review_answers')
    op.drop_table('review_answers')
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_completion_evidence_submission_id'), table_name='completion_evidence')
    op.drop_index(op.f('ix_completion_evidence_id'), table_name='completion_evidence')
    op.drop_table('completion_evidence')
    op.drop_index(op.f('ix_worker_participations_status'), table_name='worker_participations')
    op.drop_index('ix_worker_participations_lookup', table_name='worker_participations')
    op.drop_index(op.f('ix_worker_participations_inviting_worker_id'), table_name='worker_participations')
    op.drop_index(op.f('ix_worker_participations_id'), table_name='worker_participations')
    op.drop_index(op.f('ix_worker_participations_gig_id'), table_name='worker_participations')
    op.drop_index(op.f('ix_worker_participations_additional_worker_id'), table_name='worker_participations')
    op.drop_table('worker_participations')
    op.drop_table('worker_metrics')
    op.drop_index(op.f('ix_worker_experience_records_worker_id'), table_name='worker_experience_records')
    op.drop_index(op.f('ix_worker_experience_records_id'), table_name='worker_experience_records')
    op.drop_index(op.f('ix_worker_experience_records_gig_id'), table_name='worker_experience_records')
    op.drop_index('ix_worker_exp_lookup', table_name='worker_experience_records')
    op.drop_table('worker_experience_records')
    op.drop_index(op.f('ix_worker_categories_worker_id'), table_name='worker_categories')
    op.drop_index(op.f('ix_worker_categories_id'), table_name='worker_categories')
    op.drop_index(op.f('ix_worker_categories_category_id'), table_name='worker_categories')
    op.drop_table('worker_categories')
    op.drop_index(op.f('ix_worker_availability_worker_id'), table_name='worker_availability')
    op.drop_index('ix_worker_availability_lookup', table_name='worker_availability')
    op.drop_index(op.f('ix_worker_availability_id'), table_name='worker_availability')
    op.drop_index(op.f('ix_worker_availability_day_of_week'), table_name='worker_availability')
    op.drop_table('worker_availability')
    op.drop_index(op.f('ix_visitation_proposals_worker_id'), table_name='visitation_proposals')
    op.drop_index(op.f('ix_visitation_proposals_status'), table_name='visitation_proposals')
    op.drop_index(op.f('ix_visitation_proposals_id'), table_name='visitation_proposals')
    op.drop_index(op.f('ix_visitation_proposals_gig_id'), table_name='visitation_proposals')
    op.drop_table('visitation_proposals')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index('ix_reviews_reviewee', table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_gig_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reschedule_requests_status'), table_name='reschedule_requests')
    op.drop_index(op.f('ix_reschedule_requests_requested_by'), table_name='reschedule_requests')
    op.drop_index(op.f('ix_reschedule_requests_id'), table_name='reschedule_requests')
    op.drop_index(op.f('ix_reschedule_requests_gig_id'), table_name='reschedule_requests')
    op.drop_table('reschedule_requests')
    op.drop_index(op.f('ix_previous_worker_requests_worker_id'), table_name='previous_worker_requests')
    op.drop_index(op.f('ix_previous_worker_requests_status'), table_name='previous_worker_requests')
    op.drop_index(op.f('ix_previous_worker_requests_id'), table_name='previous_worker_requests')
    op.drop_index(op.f('ix_previous_worker_requests_gig_id'), table_name='previous_worker_requests')
    op.drop_index(op.f('ix_previous_worker_requests_customer_id'), table_name='previous_worker_requests')
    op.drop_table('previous_worker_requests')
    op.drop_index(op.f('ix_payments_worker_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_lookup', table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gig_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_gig_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_material_receipts_worker_id'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_id'), table_name='material_receipts')
    op.drop_index(op.f('ix_material_receipts_gig_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_gig_worker_opportunities_worker_id'), table_name='gig_worker_opportunities')
    op.drop_index(op.f('ix_gig_worker_opportunities_status'), table_name='gig_worker_opportunities')
    op.drop_index(op.f('ix_gig_worker_opportunities_id'), table_name='gig_worker_opportunities')
    op.drop_index(op.f('ix_gig_worker_opportunities_gig_id'), table_name='gig_worker_opportunities')
    op.drop_table('gig_worker_opportunities')
    op.drop_index(op.f('ix_gig_tasks_task_id'), table_name='gig_tasks')
    op.drop_index(op.f('ix_gig_tasks_id'), table_name='gig_tasks')
    op.drop_index(op.f('ix_gig_tasks_gig_id'), table_name='gig_tasks')
    op.drop_table('gig_tasks')
    op.drop_index('ix_gig_events_timeline', table_name='gig_events')
    op.drop_index(op.f('ix_gig_events_id'), table_name='gig_events')
    op.drop_index(op.f('ix_gig_events_gig_id'), table_name='gig_events')
    op.drop_index(op.f('ix_gig_events_event_type'), table_name='gig_events')
    op.drop_index(op.f('ix_gig_events_actor_id'), table_name='gig_events')
    op.drop_table('gig_events')
    op.drop_index(op.f('ix_gig_cancellations_id'), table_name='gig_cancellations')
    op.drop_index(op.f('ix_gig_cancellations_gig_id'), table_name='gig_cancellations')
    op.drop_index(op.f('ix_gig_cancellations_cancelled_by'), table_name='gig_cancellations')
    op.drop_table('gig_cancellations')
    op.drop_index(op.f('ix_conversations_worker_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_gig_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_customer_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_completion_submissions_worker_id'), table_name='completion_submissions')
    op.drop_index(op.f('ix_completion_submissions_id'), table_name='completion_submissions')
    op.drop_index(op.f('ix_completion_submissions_gig_id'), table_name='completion_submissions')
    op.drop_table('completion_submissions')
    op.drop_index(op.f('ix_completion_confirmations_id'), table_name='completion_confirmations')
    op.drop_index(op.f('ix_completion_confirmations_gig_id'), table_name='completion_confirmations')
    op.drop_index(op.f('ix_completion_confirmations_customer_id'), table_name='completion_confirmations')
    op.drop_table('completion_confirmations')
    op.drop_table('worker_profiles')
    op.drop_index(op.f('ix_gigs_status'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_selected_worker_id'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_scheduled_date'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_id'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_customer_id'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_cooperative_id'), table_name='gigs')
    op.drop_index(op.f('ix_gigs_category_id'), table_name='gigs')
    op.drop_table('gigs')
    op.drop_table('customer_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_cooperative_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_tasks_id'), table_name='service_tasks')
    op.drop_index(op.f('ix_service_tasks_category_id'), table_name='service_tasks')
    op.drop_table('service_tasks')
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_index(op.f('ix_service_categories_id'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index(op.f('ix_review_questions_id'), table_name='review_questions')
    op.drop_table('review_questions')
    op.drop_index(op.f('ix_cooperatives_id'), table_name='cooperatives')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
