"""Complete Service Categories and Tasks catalogue data defined in WAGES.md.

Categories:
1. Plumbing — ₹5/min base rate, 45-min minimum
2. Carpentry — ₹4.7/min base rate, 45-min minimum
3. Electrician — ₹5.3/min base rate, 45-min minimum
4. Painter — ₹4.2/min base rate, 45-min minimum
5. House Help — ₹3.3/min base rate, 45-min minimum
"""

from typing import List, Dict, Any, Tuple

# Per-category complexity bounds (t_min, t_max in minutes) from WAGES.md Section 2
CATEGORY_COMPLEXITY_BOUNDS: Dict[str, Tuple[int, int]] = {
    "Plumbing": (15, 180),
    "Carpentry": (20, 300),
    "Electrician": (15, 480),
    "Painter": (30, 960),
    "House Help": (20, 300),
}

CATALOGUE_DATA: List[Dict[str, Any]] = [
    {
        "name": "Plumbing",
        "description": "Professional plumbing installations, leak repairs, sanitary fittings, and pipe maintenance.",
        "base_rate_per_minute": 5.0,
        "minimum_billable_minutes": 45,
        "tasks": [
            {"name": "Leaking tap repair", "duration": 20, "base_price": 100.0},
            {"name": "Pipe leakage fix", "duration": 30, "base_price": 150.0},
            {"name": "Ceiling/wall dripping leak", "duration": 45, "base_price": 225.0},
            {"name": "Clogged drain unclogging", "duration": 25, "base_price": 125.0},
            {"name": "Toilet flush tank repair", "duration": 30, "base_price": 150.0},
            {"name": "Toilet clog removal", "duration": 20, "base_price": 100.0},
            {"name": "Toilet seat/bowl installation", "duration": 40, "base_price": 200.0},
            {"name": "Wash basin install/repair", "duration": 45, "base_price": 225.0},
            {"name": "Bathroom fitting install", "duration": 40, "base_price": 200.0},
            {"name": "Kitchen sink install/repair", "duration": 45, "base_price": 225.0},
            {"name": "Water tank install/cleaning", "duration": 60, "base_price": 300.0},
            {"name": "Water motor/pump repair", "duration": 45, "base_price": 225.0},
            {"name": "Water heater installation", "duration": 60, "base_price": 300.0},
            {"name": "Water heater repair", "duration": 40, "base_price": 200.0},
            {"name": "Pipe fitting/replacement", "duration": 40, "base_price": 200.0},
            {"name": "Bibcock/valve replacement", "duration": 20, "base_price": 100.0},
            {"name": "RO installation", "duration": 60, "base_price": 300.0},
            {"name": "RO repair/service", "duration": 30, "base_price": 150.0},
            {"name": "Drainage pipe installation", "duration": 60, "base_price": 300.0},
            {"name": "Float valve repair", "duration": 25, "base_price": 125.0},
            {"name": "Bathroom fixture install", "duration": 15, "base_price": 75.0},
            {"name": "Sewage blockage clearing", "duration": 60, "base_price": 300.0},
            {"name": "Leakage detection", "duration": 45, "base_price": 225.0},
            {"name": "Washing machine pipe fix", "duration": 20, "base_price": 100.0},
            {"name": "New pipeline install (full)", "duration": 180, "base_price": 900.0},
            {"name": "Full tap/fitting set replacement", "duration": 90, "base_price": 450.0},
        ],
    },
    {
        "name": "Carpentry",
        "description": "Woodwork, door and window fitting, cabinetry, furniture assembly, and polishing.",
        "base_rate_per_minute": 4.7,
        "minimum_billable_minutes": 45,
        "tasks": [
            {"name": "Door repair", "duration": 30, "base_price": 140.0},
            {"name": "Door installation", "duration": 90, "base_price": 425.0},
            {"name": "Window repair/install", "duration": 60, "base_price": 280.0},
            {"name": "Cupboard repair", "duration": 40, "base_price": 190.0},
            {"name": "Cupboard installation", "duration": 120, "base_price": 565.0},
            {"name": "Drawer repair/replace", "duration": 30, "base_price": 140.0},
            {"name": "Lock installation/repair", "duration": 25, "base_price": 120.0},
            {"name": "Furniture assembly", "duration": 60, "base_price": 280.0},
            {"name": "Furniture repair", "duration": 45, "base_price": 210.0},
            {"name": "Bed install/repair", "duration": 90, "base_price": 425.0},
            {"name": "Shelf installation", "duration": 30, "base_price": 140.0},
            {"name": "False ceiling work", "duration": 180, "base_price": 850.0},
            {"name": "Wooden partition install", "duration": 240, "base_price": 1130.0},
            {"name": "Curtain rod installation", "duration": 20, "base_price": 95.0},
            {"name": "Kitchen cabinet install/repair", "duration": 120, "base_price": 565.0},
            {"name": "Polishing/varnishing", "duration": 90, "base_price": 425.0},
            {"name": "Frame fitting", "duration": 60, "base_price": 280.0},
            {"name": "Plywood/laminate work", "duration": 90, "base_price": 425.0},
            {"name": "TV unit installation", "duration": 60, "base_price": 280.0},
            {"name": "Modular furniture fitting", "duration": 150, "base_price": 705.0},
            {"name": "Hinges/handles replacement", "duration": 20, "base_price": 95.0},
            {"name": "Termite damage repair", "duration": 90, "base_price": 425.0},
            {"name": "Custom furniture fabrication", "duration": 300, "base_price": 1410.0},
            {"name": "Wall shelf/rack fitting", "duration": 30, "base_price": 140.0},
        ],
    },
    {
        "name": "Electrician",
        "description": "Wiring, fixture installation, appliances, circuit breakers, and electrical safety.",
        "base_rate_per_minute": 5.3,
        "minimum_billable_minutes": 45,
        "tasks": [
            {"name": "Fan repair", "duration": 25, "base_price": 130.0},
            {"name": "Fan installation", "duration": 30, "base_price": 160.0},
            {"name": "Switchboard/socket repair", "duration": 20, "base_price": 105.0},
            {"name": "Switchboard/socket install", "duration": 30, "base_price": 160.0},
            {"name": "MCB/fuse replacement", "duration": 20, "base_price": 105.0},
            {"name": "Wiring troubleshooting", "duration": 40, "base_price": 210.0},
            {"name": "New wiring (room)", "duration": 150, "base_price": 795.0},
            {"name": "New wiring (full house)", "duration": 480, "base_price": 2545.0},
            {"name": "Light fixture installation", "duration": 20, "base_price": 105.0},
            {"name": "Light fixture repair", "duration": 20, "base_price": 105.0},
            {"name": "Tube/LED fitting", "duration": 15, "base_price": 80.0},
            {"name": "Doorbell install/repair", "duration": 20, "base_price": 105.0},
            {"name": "Inverter install/repair", "duration": 45, "base_price": 240.0},
            {"name": "Stabilizer install/repair", "duration": 30, "base_price": 160.0},
            {"name": "AC installation", "duration": 90, "base_price": 480.0},
            {"name": "AC repair/servicing", "duration": 45, "base_price": 240.0},
            {"name": "AC gas refilling", "duration": 60, "base_price": 320.0},
            {"name": "Geyser electrical connection", "duration": 30, "base_price": 160.0},
            {"name": "Chimney/exhaust fan install", "duration": 45, "base_price": 240.0},
            {"name": "Exhaust fan repair", "duration": 20, "base_price": 105.0},
            {"name": "Washing machine connection", "duration": 20, "base_price": 105.0},
            {"name": "Refrigerator repair", "duration": 45, "base_price": 240.0},
            {"name": "Microwave repair", "duration": 30, "base_price": 160.0},
            {"name": "Mixer/grinder repair", "duration": 25, "base_price": 130.0},
            {"name": "Water pump electrical repair", "duration": 30, "base_price": 160.0},
            {"name": "Extension/wiring extension", "duration": 20, "base_price": 105.0},
            {"name": "Earthing install/check", "duration": 40, "base_price": 210.0},
            {"name": "Short circuit troubleshooting", "duration": 45, "base_price": 240.0},
            {"name": "Intercom/video door phone install", "duration": 60, "base_price": 320.0},
            {"name": "CCTV installation (per camera)", "duration": 45, "base_price": 240.0},
            {"name": "Smart switch installation", "duration": 30, "base_price": 160.0},
            {"name": "Electrical safety inspection", "duration": 40, "base_price": 210.0},
        ],
    },
    {
        "name": "Painter",
        "description": "Interior and exterior wall painting, waterproofing, putty, texture, and polishing.",
        "base_rate_per_minute": 4.2,
        "minimum_billable_minutes": 45,
        "tasks": [
            {"name": "Wall painting (1 room)", "duration": 240, "base_price": 1010.0},
            {"name": "Full house painting", "duration": 960, "base_price": 4030.0},
            {"name": "Exterior wall painting", "duration": 480, "base_price": 2015.0},
            {"name": "Wall putty application", "duration": 180, "base_price": 755.0},
            {"name": "Waterproofing", "duration": 240, "base_price": 1010.0},
            {"name": "Texture/design painting", "duration": 300, "base_price": 1260.0},
            {"name": "Wood polishing/painting", "duration": 180, "base_price": 755.0},
            {"name": "Grille/gate painting", "duration": 120, "base_price": 505.0},
            {"name": "Ceiling painting", "duration": 120, "base_price": 505.0},
            {"name": "Crack filling & repair", "duration": 60, "base_price": 250.0},
            {"name": "Primer application", "duration": 120, "base_price": 505.0},
            {"name": "Wallpaper installation", "duration": 180, "base_price": 755.0},
            {"name": "Wallpaper removal", "duration": 90, "base_price": 380.0},
            {"name": "Stencil/mural painting", "duration": 240, "base_price": 1010.0},
            {"name": "Touch-up painting", "duration": 30, "base_price": 125.0},
            {"name": "Damp wall treatment", "duration": 120, "base_price": 505.0},
            {"name": "Enamel/metal furniture painting", "duration": 90, "base_price": 380.0},
            {"name": "POP work", "duration": 240, "base_price": 1010.0},
        ],
    },
    {
        "name": "House Help",
        "description": "Deep cleaning, floor care, pest control, domestic assistance, and sanitation.",
        "base_rate_per_minute": 3.3,
        "minimum_billable_minutes": 45,
        "tasks": [
            {"name": "Full house deep cleaning", "duration": 180, "base_price": 595.0},
            {"name": "Bathroom deep cleaning", "duration": 45, "base_price": 150.0},
            {"name": "Kitchen deep cleaning", "duration": 60, "base_price": 200.0},
            {"name": "Sofa cleaning", "duration": 45, "base_price": 150.0},
            {"name": "Carpet/rug cleaning", "duration": 45, "base_price": 150.0},
            {"name": "Mattress cleaning", "duration": 30, "base_price": 100.0},
            {"name": "Water tank cleaning", "duration": 60, "base_price": 200.0},
            {"name": "Utensil washing", "duration": 30, "base_price": 100.0},
            {"name": "Cooking help", "duration": 90, "base_price": 300.0},
            {"name": "Laundry & ironing", "duration": 60, "base_price": 200.0},
            {"name": "Babysitting (per hr)", "duration": 60, "base_price": 200.0},
            {"name": "Elderly care (per hr)", "duration": 60, "base_price": 200.0},
            {"name": "Pest control", "duration": 60, "base_price": 200.0},
            {"name": "Cockroach/ant treatment", "duration": 45, "base_price": 150.0},
            {"name": "Termite treatment", "duration": 120, "base_price": 400.0},
            {"name": "Move-in/out cleaning", "duration": 240, "base_price": 795.0},
            {"name": "Post-construction cleaning", "duration": 300, "base_price": 995.0},
            {"name": "Window/glass cleaning", "duration": 30, "base_price": 100.0},
            {"name": "Balcony/terrace cleaning", "duration": 30, "base_price": 100.0},
            {"name": "Fridge/microwave interior cleaning", "duration": 20, "base_price": 65.0},
            {"name": "Car washing", "duration": 30, "base_price": 100.0},
            {"name": "Gardening/plant care", "duration": 45, "base_price": 150.0},
            {"name": "Society common area cleaning", "duration": 90, "base_price": 300.0},
            {"name": "Daily domestic help (per visit)", "duration": 120, "base_price": 400.0},
        ],
    },
]
